USE master
GO

CREATE DATABASE TodoDb;
GO

USE TodoDb;
GO

CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT (GETDATE())
);

CREATE TABLE Categories (
    CategoryId UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name VARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT (GETDATE()),

    FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE TABLE Todos (
    TodoId UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    CategoryId UNIQUEIDENTIFIER NULL,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(MAX) NULL,
    IsCompleted BIT DEFAULT 0,
    ReminderTime DATETIME NULL,
    CreatedAt DATETIME DEFAULT (GETDATE()),
    UpdatedAt DATETIME DEFAULT (GETDATE()),

    FOREIGN KEY (UserId) REFERENCES Users(UserId),
    FOREIGN KEY (CategoryId) REFERENCES Categories(CategoryId)
);
